---
output: 
  html_document:
    css: style.css
    self_contained: no
    toc: false
---

<center>
<hr style="height:2px;border:none;color:#333;background-color:#333;" />
</center>

<center>
<h1> Comparação de modelos pela verossimilhança </h1>
CE092 - Extensões de Modelos de Regressão  
Universidade Federal do Paraná  
Data
</center>

<center>
<hr style="height:2px;border:none;color:#333;background-color:#333;" />
</center>  

```{r setup, include=FALSE}
##-----------------------------------------------------------------------------
## Knitr settings. Do not run.
library(knitr)
opts_chunk$set(
    tidy=FALSE,
    cache = TRUE,
    cache.path = "cache/",
    fig.path = "figures/",
    echo=TRUE,
    message=FALSE,
    error=FALSE,
    warning=FALSE,
    fig.align='center')
options(width=70)

```

## Criando funções 


```{r}
##-------------------------------------------
## Transformação boxcox
transf.boxcox <- function(y, lambda){
    if(lambda == 0) yt <- log(y)
    else yt <- ((y ^ lambda) - 1) / lambda
    return(yt)
}

##-------------------------------------------
## Jacobiano da tranformação boxcox
jacobiano.boxcox <- function(y, lambda, log = T){
    if(lambda != 0){
        ljac <- ((1 / lambda) - 1) * log(lambda * y + 1)
    } else ljac <- y
    if(log) return(sum(ljac))
    else return(sum(exp(ljac)))
}

##-------------------------------------------
## Funcções de log-verossimilhanças
ll.general <- function(par, y, distr = "normal"){
    switch(distr,
           "normal" = {
               mu <- par[1]; sig <- par[2]
               ll <- dnorm(y, mean = mu, sd = sig, log = T)
           },
           "log-normal" = {
               mulog <- par[1]; siglog <- par[2]
               ll <- dlnorm(y, meanlog = mulog, sdlog = siglog, log = T)
           },
           "gamma" = {
               shape <- par[1]; scale = par[2]
               ll <- dgamma(y, shape = shape, scale = scale, log = T)
           })
    return(-sum(ll))
}
```

## Conjunto de Dados

```{r}
##-------------------------------------------
## Dados
y <- c(5.0, 9.5, 9.8, 7.4, 18.2, 8.3, 7.0, 8.2, 7.4, 4.9, 12.5, 15.3,
       8.9, 12.2, 22.2, 1.0, 8.9, 7.3, 4.6, 3.9)
yt <- transf.boxcox(y, 0.2)

par(mfrow = c(1, 2))
hist(y, prob = T, col = 'darkgray', border = 'white', main = "")
hist(yt, prob = T, col = 'darkgray', border = 'white', main = "")
```

## Estimação

```{r}
##-------------------------------------------
## Estimação

## Normal com variavel original
y.norm.max <- optim(c(10, 1), ll.general, y = y, distr = "normal",
                    method = "L-BFGS-B", lower=c(-Inf, 1e-10))

## Normal com a variavel transformada
yt.norm.max <- optim(c(10, 1), ll.general, y = yt, distr = "normal",
                     method = "L-BFGS-B", lower=c(-Inf, 1e-10))

## Log-Normal com variavel original
y.lnorm.max <- optim(c(10, 1), ll.general, y = y, distr = "log-normal",
                     method = "L-BFGS-B", lower=c(-Inf, 1e-10))

## Normal com variavel transformada (log(y)) equivalente acima
yl.norm.max <- optim(c(10, 1), ll.general, y = log(y),
                     distr = "normal",
                     method = "L-BFGS-B", lower=c(-Inf, 1e-10))

## Gamma com variavel original
y.gamma.max <- optim(c(10, 1), ll.general, y = y, distr = "gamma",
                     method = "L-BFGS-B", lower=c(1e-10, 1e-10))

tab <- cbind("Normal/y" = c(y.norm.max$par, -y.norm.max$value),
             "Normal/yt" = c( yt.norm.max$par, -yt.norm.max$value),
             "Normal/yl" = c(yl.norm.max$par, -yl.norm.max$value),
             "Log-Normal/y" = c(y.lnorm.max$par, -y.lnorm.max$value),
             "Gamma/y" = c(y.gamma.max$par, -y.gamma.max$value))
rownames(tab) <- c("theta1", "theta2", "loglik")

tab
```

## Escalonando as log-verossilhanças para comparação

```{r}
##-------------------------------------------
## Comparacao

## Tornando a verossimilhanca do modelo com v.a. tranformada comparável
## com os demais modelos
loglik.compare <- rbind(
    "Normal/y" = -y.norm.max[[2]],
    "Normal/yt" = -yt.norm.max[[2]] - jacobiano.boxcox(yt, 0.2),
    "Normal/yl" = -yl.norm.max[[2]] - jacobiano.boxcox(log(y), 0),
    "Log-Normal/y" = -y.lnorm.max[[2]],
    "Gamma/y" = -y.gamma.max[[2]])

loglik.compare
```

## Comparando os ajustes graficamente

```{r, fig.height = 12, fig.width = 12}
##-------------------------------------------
## Obervando os ajustes
par(mfrow = c(3, 2))

hist(y, prob = T, col = 'darkgray', border = 'white', main = "")
mtext(text = "1. Normal/y", adj = 0.9, cex = 1.3, line = - 4)
mtext(sprintf("Log-verossimilhança: %.2f", loglik.compare[1]))
with(y.norm.max, curve(
    dnorm(x, mean = par[1], sd = par[2]), add = T, col = 4, lwd = 2))

hist(yt, prob = T, col = 'darkgray', border = 'white', main = "")
mtext(text = "2. Normal/yt", adj = 0.9, cex = 1.3, line = - 4)
mtext(sprintf("Log-verossimilhança: %.2f", loglik.compare[2]))
with(yt.norm.max, curve(
    dnorm(x, mean = par[1], sd = par[2]), add = T, col = 4, lwd = 2))

hist(log(y), prob = T, col = 'darkgray', border = 'white', main = "")
mtext(text = "3. Normal/yl", adj = 0.9, cex = 1.3, line = - 4)
mtext(sprintf("Log-verossimilhança: %.2f", loglik.compare[3]))
with(yl.norm.max, curve(
    dnorm(x, mean = par[1], sd = par[2]), add = T, col = 4, lwd = 2))

hist(y, prob = T, col = 'darkgray', border = 'white', main = "")
mtext(text = "4. Log-Normal/y", adj = 0.9, cex = 1.3, line = - 4)
mtext(sprintf("Log-verossimilhança: %.2f", loglik.compare[4]))
with(y.lnorm.max, curve(
    dlnorm(x, mean = par[1], sd = par[2]), add = T, col = 4, lwd = 2))

hist(y, prob = T, col = 'darkgray', border = 'white', main = "")
mtext(text = "5. Gamma/y", adj = 0.9, cex = 1.3, line = - 4)
mtext(sprintf("Log-verossimilhança: %.2f", loglik.compare[5]))
with(y.gamma.max, curve(
    dgamma(x, shape = par[1], scale = par[2]), add = T, col = 4, lwd = 2))

plot(0, 0, type = "n", axes = F, bty = "n", xlab = "", ylab = "")
text <- "
1. Modelo normal para os dados originais\n
2. Modelo normal para os dados tranformados\n
3. Modelo normal para os dados tranformados\n
4. Modelo log-normal para os dados originais\n
5. Modelo gamma para os dados originais"
mtext(text = text, padj = 1, adj = 0, at = -1)
```
